<?php
$columnsKey=array_keys($columns);
$IsCustomSearch=false;
$ArrayInput=array();
foreach($columns as $key =>$val)
{
    $ArrayInput[$key]=[];
    if(array_key_exists("search",$val) &&( array_keys($val['search']) !== range(0, count($val['search']) - 1))){
        $ArrayInput[$key]=$val['search'];
        $IsCustomSearch=true;
    }
}
?>
<div class="col-md-12">
    <table class="table table-striped table-bordered" id="datatable_<?php echo $ref?>">
        <thead>
        <tr role="row" class="heading">
            <?php
            foreach($columns as $key =>$val)
            {
                ?>
                <th class="datatable datatable_cl_<?php echo $ref?>_<?php echo $key?>" >
                   <?php  echo array_key_exists("label",$val) ? $val['label'] : $key?>
                 </th>
                <?php
            }
            ?>
        </tr>
        <?php
        if($IsCustomSearch){
           ?>
        <tr role="row" class="filter">
            <?php
                foreach($ArrayInput as $key=>$InputConfig){
                    echo"<td>";
                    if(empty($InputConfig)){

                    }
                    else{
                           if(array_key_exists("attr",$InputConfig) && array_key_exists("name",$InputConfig['attr'])){
                               unset($InputConfig['attr']['name']);
                           }

                           if(array_key_exists("attr",$InputConfig) && array_key_exists("type",$InputConfig['attr'])){
                               unset($InputConfig['attr']['type']);
                           }
                            $filtertype=strtolower (array_key_exists("type",$InputConfig) ? $InputConfig['type'] :"text");
                           switch($filtertype){
                               case "date" :;
                               case "datetime" :;
                               case "email" :;
                               case "number" :;
                               case "range" :;
                               case "tel" :;
                               case "time" :;
                               case "url" :;
                               case "datetime-local":;
                               case "text" :
                                   echo "<input type='$filtertype' name='input_".str_replace("_","-",$ref)."_".$key."'";
                                   if(is_array($InputConfig['attr'])){
                                       $InputConfigAttr=$InputConfig['attr'];

                                       foreach($InputConfigAttr as $_key=>$_val){
                                           echo " $_key='$_val' ";
                                       }
                                   }

                                   echo "/>";
                                   ;break;
                               case "select":
                                   echo "<select name='input_".str_replace("_","-",$ref)."_".$key."' ";
                                   if(is_array($InputConfig['attr'])){
                                       $InputConfigAttr=$InputConfig['attr'];

                                       foreach($InputConfigAttr as $_key=>$_val){
                                           echo " $_key='$_val' ";
                                       }
                                   }
                                   echo ">";
                                   if(array_key_exists("options",$InputConfig) && array_key_exists("items",$InputConfig['options'])){
                                        foreach($InputConfig['options']['items'] as $keyitem =>$itemvalue){
                                            echo "<option value='$keyitem' ";
                                            if(array_key_exists("default",$InputConfig['options']) && $keyitem==$InputConfig['options']['default']){
                                                 echo " selected='selected'";
                                            }
                                            echo ">$itemvalue</option>";
                                        }
                                   }
                                   echo"</select>";
                                   ;break;
                               case "between":

                                   ;break;
                           }


                    }
                    echo"</td>";
                }
            ?>
        </tr>
        <?php
        }
        ?>
        </thead>
        <tbody>
        <?php
        if(! $ajax)
        foreach($paginator as $item){
            ?>
            <tr>
                <?php

                foreach($columnsKey as $key){
                    ?>
                        <td>
                            <?php
                            if(is_object($item) &&  property_exists ($item,$key)){
                                echo $item->{$key};
                            }
                            if(is_array($item) &&  array_key_exists ($key,$item)){
                                echo $item[$key];
                            }?>
                        </td>
                    <?php
                }
                ?>
            </tr>
        <?php
        }
        ?>
        </tbody>
    </table>
</div>